platform: linux

inputs:
- service_creds

params:
  CREDHUB_CA_CERT: ((CREDHUB_CA_CERT))
  CREDHUB_SECRET: ((CREDHUB_SECRET))
  CREDHUB_CLIENT: ((CREDHUB_CLIENT))
  CREDHUB_SERVER: ((CREDHUB_SERVER))

run:
  path: bash
  args:
  - -euo
  - pipefail
  - -c
  - |
    creds="$( jq -r '.gcp_credentials_json' service_creds/metadata )"

    if [ "$creds" == "null" ]; then
      echo "Creds have not changed, skipping..."
      exit 0
    fi

    credhub set --type value --value "$creds" --name ((name))