platform: linux

inputs:
- name: kubeconfig

params:
 API_USERNAME: ((api_user))
 API_PASSWORD: ((api_password))
 DB_USERNAME: ((db_user))
 DB_PASSWORD: ((db_password))
run:
  path: bash
  args:
  - -euo
  - pipefail
  - -c
  - |
    source kubeconfig/source
    export config="$(cat << EOF
    gcp:
      credentials: ""
      project: ((project_id))
    db:
      host: 127.0.0.1
      password: ${DB_PASSWORD}
      user: ${DB_USERNAME}
      tls: false
    api:
      user: ${API_USERNAME}
      password: ${API_PASSWORD}
    EOF
    )"
    curl https://storage.googleapis.com/kf-releases/csb/v1.0.0/kf-csb.yaml \
    | sed \
      -e "s|<GSA_NAME>|((service_account_email))|g" \
      -e "s|<INSTANCE_CONNECTION_NAME>|((instance_connection_name))|g" \
      -e "s|<DB_PORT>|3306|g" > manifest.yml
    echo -ne "\n---\n" >> manifest.yml
    kubectl create namespace kf-csb --dry-run=client -o yaml >> manifest.yml
    echo "---" >> manifest.yml
    kubectl create secret generic csb-secret --namespace kf-csb --from-literal=config.yml="$config" --dry-run=client -o yaml >> manifest.yml
    kubectl apply -f manifest.yml
