platform: linux

inputs:
- name: kubeconfig

run:
  path: bash
  args:
  - -euo
  - pipefail
  - -c
  - |
    source kubeconfig/source

    set -x

    kubectl \
      apply \
      --filename \
      "https://storage.googleapis.com/tekton-releases/pipeline/previous/v((tekton_version))/release.yaml"

    kubectl \
      --namespace tekton-pipelines \
      annotate ServiceAccount \
      --overwrite=true \
      --selector=app.kubernetes.io/part-of=tekton-pipelines \
      iam.gke.io/gcp-service-account=((service_account_email))