platform: linux

inputs:
- name: asmcli

params:
  GOOGLE_CREDENTIALS:
  GOOGLE_APPLICATION_CREDENTIALS: creds.json

run:
  path: bash
  args:
  - -euo
  - pipefail
  - -c
  - |
    echo "${GOOGLE_CREDENTIALS}" > creds.json

    gcloud \
      auth \
      activate-service-account \
      --key-file "$GOOGLE_APPLICATION_CREDENTIALS" \
      --project '((project_id))'
    
    project_number="$( gcloud projects describe "((project_id))" --format="value(projectNumber)" )"
    sed -i "s/PROJECT_NUMBER=\"\"/PROJECT_NUMBER=\"${project_number}\"/g" ./asmcli/asmcli

    ./asmcli/asmcli install \
      --project_id ((project_id)) \
      --cluster_name ((cluster_name)) \
      --cluster_location ((zone)) \
      --enable_all \
      --ca mesh_ca \
      --option legacy-default-ingressgateway