platform: linux

image_resource:
  type: registry-image
  source: {repository: engineerbetter/pcf-ops}

inputs:
- name: kubeconfig

run:
  path: bash
  args:
  - -euo
  - pipefail
  - -c
  - |
    source kubeconfig/source
    export config="$(cat << EOF
    gcp:
      credentials: ""
      project: ((project_id))
    db:
      host: ((instance_connection_name))
      password: ((db_password))
      user: ((db_user))
      tls: false
    api:
      user: ((api_user))
      password: ((api_password))
    EOF
    )"
    curl https://storage.googleapis.com/kf-releases/csb/v1.0.0/kf-csb.yaml \
    | sed \
      -e "s|<GSA_NAME>|((service_account_email))|g" \
      -e "s|<INSTANCE_CONNECTION_NAME>|((instance_connection_name))|g" \
      -e "s|<DB_PORT>|3306|g" > manifest.yml
    echo "---" >> manifest.yml
    kubectl create namespace kf-csb --dry-run=client -o yaml >> manifest.yml
    echo "---" >> manifest.yml
    kubectl create secret generic csb-secret --namespace kf-csb --from-literal=config.yml="$config" --dry-run=client -o yaml >> manifest.yml
    kubectl apply -f manifest.yml
