platform: linux

inputs:
- name: kubeconfig

run:
  path: bash
  args:
  - -euo
  - pipefail
  - -c
  - |
    source kubeconfig/source
    kf target ((space))
    if kf apps | grep -q ((app_name)); then
      kf delete ((app_name))
      exit 0
    fi
      echo "((app_name)) not found. Nothing to do."