platform: linux

inputs:
- name: kubeconfig
run:
  path: bash
  args:
  - -euo
  - pipefail
  - -c
  - |
    source kubeconfig/source
    if kubectl get -n ((namespace)) rec  | grep -q ((cluster_name)); then
      kubectl delete  -n ((namespace)) rec ((cluster_name))
      exit 0
    fi
    echo "Redis Cluster not found. Nothing to do."


